default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: qkspace_development

test:
  <<: *default
  database: qkspace_test

production:
  user: deploy
  database: myapp
  password: <%= Rails.application.credentials.dig(:database, :password) %>
